# Generated by Django 3.0.8 on 2020-07-14 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReitingM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='film',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ReitingM.Film'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='film',
            name='preview',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.TextField(max_length=1000),
        ),
    ]
