# Generated by Django 3.0.8 on 2020-07-14 09:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReitingM', '0002_auto_20200714_0439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='film',
        ),
        migrations.AddField(
            model_name='feedback',
            name='film_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ReitingM.Film', verbose_name='Film'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='positiv',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.PositiveIntegerField(default=8, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.TextField(max_length=1000, verbose_name='Your feedback'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=70, verbose_name='Nickname'),
        ),
        migrations.AlterField(
            model_name='film',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Poster'),
        ),
        migrations.AlterField(
            model_name='film',
            name='preview',
            field=models.TextField(max_length=500, null=True, verbose_name='Summary'),
        ),
    ]
